plugins {
    id 'java'
}

group = 'ru.alfa'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.datafaker:datafaker:1.9.0'
    implementation 'com.github.lalyos:jfiglet:0.0.8'

    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // Cucumber для Java
    testImplementation 'io.cucumber:cucumber-java:7.14.1'

    // Cucumber для интеграции с JUnit 5
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.14.1'

    testImplementation 'org.junit.platform:junit-platform-suite:1.9.1'

    // Нужно для запуска JUnit 5 тестов
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-encoding' << 'UTF-8'
}

test {
    useJUnitPlatform()

    systemProperty "cucumber.filter.tags", System.getProperty("cucumber.filter.tags")

    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
        showStandardStreams = true
    }
}